### ISSUE TITLE
unable to run app

### ISSUE THREAD

**Issue by mokendkomer** [mijorus/whisper#23]
```
❯ flatpak run it.mijorus.whisper
Traceback (most recent call last):
  File "/app/bin/whisper", line 45, in <module>
    from whisper import main
  File "/app/share/whisper/whisper/main.py", line 22, in <module>
    from .window import WhisperWindow
  File "/app/share/whisper/whisper/window.py", line 23, in <module>
    from .components.PwConnectionBox import PwConnectionBox
  File "/app/share/whisper/whisper/components/PwConnectionBox.py", line 6, in <module>
    from ..utils.utils import link_output_input
  File "/app/share/whisper/whisper/utils/utils.py", line 28
    return set(listA) - set(listB) | set(listB) - set(listA)create_pulse_events_listener
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax
```

I'm running fedora 39.

**Comment by mokendkomer** [comment]
Upon investigating, it looks like @AppleMayExist's pull request fixes it. Thank you for the app!

**Comment by mijorus** [comment]
It does, I'm releasing the fix now
