### ISSUE TITLE
Whisper flatpak 1.2.1 flatpak fails to start due to _parse_pwlink_return on Fedora 40

### ISSUE THREAD

**Issue by luminoso** [mijorus/whisper#24]
Version: 1.2.1

I think it started to happen after upgrading to Fedora 40, but I'm not 100% sure.
I tried to reinstall, with no success.

Traceback:

```
$ flatpak run it.mijorus.whisper

(process:2): Gtk-WARNING **: 09:09:43.483: Locale not supported by C library.
        Using the fallback 'C' locale.
Logging to file: /home/luminoso/.var/app/it.mijorus.whisper/cache/logs/whisper.log
Traceback (most recent call last):
  File "/app/share/whisper/whisper/main.py", line 77, in do_activate
    win = WhisperWindow(application=self)
  File "/app/share/whisper/whisper/window.py", line 112, in __init__
    self.connection_box = self.create_connection_box()
  File "/app/share/whisper/whisper/window.py", line 165, in create_connection_box
    pw_connection_box = PwConnectionBox()
  File "/app/share/whisper/whisper/components/PwConnectionBox.py", line 22, in __init__
    for k, v in Pipewire.list_outputs().items():
  File "/app/share/whisper/whisper/pipewire/pipewire.py", line 126, in list_outputs
    items = Pipewire._parse_pwlink_return(output)
  File "/app/share/whisper/whisper/pipewire/pipewire.py", line 74, in _parse_pwlink_return
    name, ch = line.split(':')
ValueError: not enough values to unpack (expected 2, got 1)
Exception in thread Thread-1 (_startup_logs):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/share/whisper/whisper/window.py", line 145, in _startup_logs
    for k, v in Pipewire.list_outputs().items():
  File "/app/share/whisper/whisper/pipewire/pipewire.py", line 126, in list_outputs
    items = Pipewire._parse_pwlink_return(output)
  File "/app/share/whisper/whisper/pipewire/pipewire.py", line 74, in _parse_pwlink_return
    name, ch = line.split(':')
ValueError: not enough values to unpack (expected 2, got 1)
```

Attached `/home/luminoso/.var/app/it.mijorus.whisper/cache/logs/whisper.log` : [whisper.log](https://github.com/mijorus/whisper/files/14993765/whisper.log)

**Comment by mijorus** [comment]
version 1.2.2 should address this issue

**Comment by luminoso** [comment]
I'm on 1.2.3 and it looks like this:

![image](https://github.com/mijorus/whisper/assets/296323/e7d48bb7-b3ca-4a18-98be-9b9de2ee3531)

debug log: [whisper.log](https://github.com/mijorus/whisper/files/15161820/whisper.log)

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
